# Generated by Django 4.0.3 on 2022-03-17 09:23

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_rename_note_name_note_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='note',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
